#!/usr/bin/perl
# Generate markov chains from an input corpus
use warnings;
use strict;
use Data::Dumper;

my %chain;
undef $/;
my $input = <>;
$input = lc $input;

#$input =~ s/[.,;:]//msg;

my @words = split /\s+/, $input;

for(my $i = 0 ; $i < @words ; $i++)
{
	push @{ $chain{$words[$i]} ||= [] }, $words[$i+1];
}

my @k = keys %chain;
my $w = $k[rand @k];

#print Dumper(\%chain);


sub choose
{
	my $w = shift;
	my $next = $chain{$w}
		or return;
	return $next->[rand @$next];
}
	
while(1)
{
	print $w, "\n";

	last if $w =~ m/[^.][.?]$/;

	$w = choose($w) or last;
}
